/**
 * Все подписи интерфейса на русском.
 * Чтобы сменить язык позже — правьте только этот файл.
 */
export const t = {
  appTitle: "Расходы: Китай",
  settings: "Настройки",
  back: "Назад",
  loading: "Загрузка…",
  addExpense: "Добавить расход",
  addExpenseButton: "+ Добавить расход",
  whoPaid: "Кто платил",
  amountCny: "Сумма (CNY ¥)",
  noteOptional: "Заметка (необязательно)",
  amountPlaceholder: "Напр.: 120",
  notePlaceholder: "Напр.: ужин, такси…",
  invalidAmount: "Введите корректную сумму (CNY)",
  history: "История",
  noExpenses: "Расходов пока нет. Добавьте первую запись выше.",
  delete: "Удалить",
  today: "Сегодня",
  remainingToday: "Остаток на сегодня",
  spentToday: "Потрачено сегодня",
  tripTotal: "Всего за поездку",
  notTripDay: "Сегодня не входит в даты поездки (см. Настройки).",
  dailyBudget: "Бюджет на сегодня",
  overBudget: "Превышение бюджета",
  spendingByPerson: "Расходы сегодня по человеку",
  loadMock: "Загрузить примеры (тест)",
  cloudNotConfigured: "Облако не настроено — данные только на этом устройстве.",
  cloudSaveFailed: "Не удалось сохранить в облако",
  zaloTitle: "Импорт из Zalo",
  zaloTabScreenshot: "Скриншот",
  zaloTabText: "Текст",
  zaloScreenshotHow: "Скриншот чата Zalo",
  zaloScreenshotStep1: "Откройте чат поездки в Zalo.",
  zaloScreenshotStep2:
    "Сделайте скриншот (кнопки питания + громкость на iPhone, или жест на Android).",
  zaloScreenshotStep3: "Загрузите фото чека или чата → «Разобрать скриншот».",
  zaloScreenshotHint:
    "На чеках часто нет знака ¥ — подойдёт строка 合计 / 总计 / 实付 или итоговая сумма. Нужен OPENAI_API_KEY в Vercel. JPG, PNG, WebP, до 4 МБ.",
  zaloPickImages: "📷 Выбрать скриншот(ы)",
  zaloFilesSelected: "Выбрано файлов: {n}",
  zaloParseScreenshot: "Разобрать скриншот",
  zaloParsedVision: "Разобрано со скриншота (ИИ).",
  zaloHowTitle: "Как скопировать чат Zalo",
  zaloStep1: "Откройте групповой чат поездки в Zalo.",
  zaloStep2: "Долгое нажатие на сообщение → «Копировать» (или выделите несколько).",
  zaloStep3: "Вставьте текст в поле ниже.",
  zaloStep4: "Нажмите «Разобрать» → проверьте → «Добавить».",
  zaloPasteLabel: "Текст из чата",
  zaloPastePlaceholder:
    "Anna: обед 120 yuan\nKostya: такси ¥45\n…",
  zaloParseButton: "Разобрать сообщения",
  zaloParsing: "Разбор…",
  zaloParseError: "Не удалось разобрать",
  zaloParsedAi: "Разобрано с помощью ИИ.",
  zaloParsedSimple: "Разобрано простым парсером.",
  zaloNothingFound:
    "Сумма не найдена. Для чека: сфотографируйте итог (合计, 总计, 实付) или всю квитанцию. Для чата: укажите число и кто платил.",
  zaloPreview: "Найденные расходы",
  zaloAddSelected: "Добавить выбранные ({n})",
  zaloAddedCount: "Добавлено расходов: {n}",
  settingsTripStart: "Дата начала поездки",
  settingsTripEnd: "Дата окончания поездки",
  settingsDailyBudget: "Дневной бюджет (CNY — на всех 3)",
  settingsRate: "Курс: 1 CNY = ? VND",
  settingsHint:
    "Каждый новый день дневной бюджет сбрасывается. Расходы группируются по дате на вашем устройстве.",
  saveSettings: "Сохранить настройки",
  saved: "Сохранено ✓",
  dataSection: "Данные",
  dataHint:
    "Расходы хранятся в облаке (Supabase). Anna, Kostya и Taya по одной ссылке видят одни и те же данные.",
  clearConfirm: "Удалить все расходы? Это нельзя отменить.",
  clearAll: "Удалить все расходы",
  zaloLink: "Импорт из Zalo",
  mockLunch: "Обед",
  mockDrinks: "Напитки",
} as const;
