/**
 * Все подписи интерфейса на русском.
 * Чтобы сменить язык позже — правьте только этот файл.
 */
export const t = {
  appTitle: "Расходы: Китай",
  settings: "Настройки",
  back: "Назад",
  loading: "Загрузка…",
  addExpense: "Добавить расход",
  addExpenseButton: "+ Добавить расход",
  whoPaid: "Кто платил",
  amountCny: "Сумма (CNY ¥)",
  noteOptional: "Заметка (необязательно)",
  amountPlaceholder: "Напр.: 120",
  notePlaceholder: "Напр.: ужин, такси…",
  invalidAmount: "Введите корректную сумму (CNY)",
  history: "История",
  noExpenses: "Расходов пока нет. Добавьте первую запись выше.",
  delete: "Удалить",
  today: "Сегодня",
  remainingToday: "Остаток на сегодня",
  spentToday: "Потрачено сегодня",
  tripTotal: "Всего за поездку",
  notTripDay: "Сегодня не входит в даты поездки (см. Настройки).",
  dailyBudget: "Бюджет на сегодня",
  overBudget: "Превышение бюджета",
  spendingByPerson: "Расходы сегодня по человеку",
  loadMock: "Загрузить примеры (тест)",
  syncLocalOnly:
    "Только на этом устройстве — нужны Vercel + Supabase для общего доступа",
  syncLoading: "Загрузка общих данных…",
  syncSaving: "Сохранение…",
  syncOk: "Облако — у всех одни и те же данные",
  syncError: "Ошибка синхронизации",
  syncOffline: "Офлайн / облако не настроено",
  cloudNotConfigured: "Облако не настроено — данные только на этом устройстве.",
  cloudSaveFailed: "Не удалось сохранить в облако",
  settingsTripStart: "Дата начала поездки",
  settingsTripEnd: "Дата окончания поездки",
  settingsDailyBudget: "Дневной бюджет (CNY — на всех 3)",
  settingsRate: "Курс: 1 CNY = ? VND",
  settingsHint:
    "Каждый новый день дневной бюджет сбрасывается. Расходы группируются по дате на вашем устройстве.",
  saveSettings: "Сохранить настройки",
  saved: "Сохранено ✓",
  dataSection: "Данные",
  dataHint:
    "Расходы хранятся в облаке (Supabase). Anna, Kostya и Taya по одной ссылке видят одни и те же данные.",
  clearConfirm: "Удалить все расходы? Это нельзя отменить.",
  clearAll: "Удалить все расходы",
  step2: "Шаг 2: импорт из Zalo + ИИ (скоро)",
  mockLunch: "Обед",
  mockDrinks: "Напитки",
} as const;
